services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    hostname: oracle
    container_name: oracle
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: testing
    volumes:
      - ./docker/oracle/setup:/container-entrypoint-initdb.d

  myquery:
    image: jeffersonlab/myquery:4.0.0
    hostname: myquery
    container_name: myquery
    ports:
      - "8082:8080"
      - "9992:9990"

  mya:
    image: jeffersonlab/mycontainer:1.1.0
    hostname: mya
    container_name: mya
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # If localhost, then rfd server tries to connect to itself and finds no one listening.  Need to expose
      # keycloak port, and use dev system hostname to direct traffic to the proper system/port
      #KEYCLOAK_FRONTEND_HOSTNAME: <YOUR_SYSTEM_HOSTNAME>
      KEYCLOAK_FRONTEND_PORT: '8081'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      KEYCLOAK_HOME: '/opt/keycloak'
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'RFDashboard'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
    volumes:
      - ./docker/keycloak:/scripts
    entrypoint: /scripts/docker-entrypoint.sh

  puppet:
    image: slominskir/puppet-show:2.1.1
    hostname: puppet
    container_name: puppet
    ports:
      - "3000:3000"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    hostname: mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"