ALTER TABLE MOD_ANODE_HARVESTER_LINAC_SCAN
  ADD (
    TRIPS_PER_HOUR_N        NUMBER(15,8),
    TRIPS_PER_HOUR_NO_MAV_N NUMBER(15,8)
  );

UPDATE MOD_ANODE_HARVESTER_LINAC_SCAN
  SET 
    TRIPS_PER_HOUR_N = TO_NUMBER(TRIPS_PER_HOUR),
    TRIPS_PER_HOUR_NO_MAV_N = TO_NUMBER(TRIPS_PER_HOUR_NO_MAV);

-- Probably not needed, but it seemed to help at one point in debugging stuff.  
COMMIT;

ALTER TABLE MOD_ANODE_HARVESTER_LINAC_SCAN
  DROP (
    TRIPS_PER_HOUR,
    TRIPS_PER_HOUR_NO_MAV
  );
  
ALTER TABLE MOD_ANODE_HARVESTER_LINAC_SCAN RENAME COLUMN TRIPS_PER_HOUR_N TO TRIPS_PER_HOUR;
ALTER TABLE MOD_ANODE_HARVESTER_LINAC_SCAN RENAME COLUMN TRIPS_PER_HOUR_NO_MAV_N TO TRIPS_PER_HOUR_NO_MAV;
