name: Update DockerHub Description
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/docker-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.head_ref }}-ci
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v3
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: jeffersonlab/${{ github.event.repository.name }}
          short-description: ${{ github.event.repository.description }}
